name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make Amethyst better? Let me know!
        
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What would you like to see added?
      placeholder: "Make server icons hexagonal instead of circular"
    validations:
      required: true
      
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why would this be useful?
      placeholder: "Hexagons would match the modern Discord aesthetic better"
    validations:
      required: false
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered other approaches?
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Mockups, examples from other themes, etc.
    validations:
      required: false
